# Generated by Django 4.0.4 on 2022-06-30 15:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bibliografia',
            field=models.TextField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
